#!/usr/bin/env ruby

input = ARGV # ARGV holds the command line arguments that were passed in

if input.empty?
  print "I'd cheer for you, if only I knew who you were :("
else
  parsed_input = input[0][/[a-zA-Z]*(-)?[a-zA-Z]*/]
  if input.size == 1 && input[0].empty?
    print "I'd cheer for you, if only I knew who you were :("
  elsif input[0].size == parsed_input.size
    input_caps = input[0].upcase
    input_caps.each_char { |x|
      if !!/A|E|I|O|U/.match(x)
        puts "Give me an... #{x}" 
      elsif !!/-/.match(x)
        #if name has dash, do nothing
      else
        puts "Give me a... #{x}" 
      end
    }
    puts "#{input_caps}'s just GRAND!"
  elsif input.size == 2
    print "has two args"
  else
    print "I'd cheer for you, if only I knew who you were :("
  end
end


