#!/usr/bin/env ruby

input = ARGV # ARGV holds the command line arguments that were passed in


if input.size == 0 && input.empty?
  print "I'd cheer for you, if only I knew who you were :("
elsif !!/\d/.match(input[0]) && input[1].nil?
  print "I'd cheer for you, if only I knew who you were :("
elsif !!/\s/.match(input[0]) && input[1].nil?
  print "I'd cheer for you, if only I knew who you were :("
elsif !!/\W/.match(input[0]) && !!/\W/.match(input[1])
  puts "I'd cheer for you, if only I knew who you were :("
  puts "I would wish you a Happy Birthday, if I knew when that was!"
else
  parsed_input = input[0][/[a-zA-Z]*(-)?[a-zA-Z]*/]
  if input.size == 1 && input[0].empty?
    print "I'd cheer for you, if only I knew who you were :("
  elsif (input[0].size == parsed_input.size) && (input.size == 1)
    input_caps = input[0].upcase
    input_caps.each_char { |x|
      if !!/A|E|I|O|U/.match(x)
        puts "Give me an... #{x}"
      elsif !!/-/.match(x)
        #if name has dash, don't print the dash in the cheer
      else
        puts "Give me a... #{x}"
      end
    }
    puts "#{input_caps}'s just GRAND!"
  elsif input.size == 2
    if (!/\w+/.match(input[0]) && !/\w+(-)\w+/.match(input[0])) && !/\d{2}(\/)\d{2}/.match(input[1])
      print "I'd cheer for you, if only I knew who you were :("
      print "I would wish you a Happy Birthday, if I knew when that was!"
      exit
    elsif !/\d{2}(\/)\d{2}/.match(input[1])
      print "I would wish you a Happy Birthday, if I knew when that was!"
      exit
    end
    input_caps = input[0].upcase
    input_caps.each_char { |x|
      if !!/A|E|I|O|U/.match(x)
        puts "Give me an... #{x}"
      elsif !!/-/.match(x)
        #if name has dash, don't print the dash in the cheer
      else
        puts "Give me a... #{x}"
      end
    }
    puts "#{input_caps}'s just GRAND!"
    if !!/\d{2}(\/)\d{2}/.match(input[1])
      require 'date'
      today = Date.today
      bday = Date.parse(input[1])
      year = bday.year
      month = bday.month
      day = bday.mday
      parsed_date = Date.valid_date?(year,month,day)
      if parsed_date == true
        relational = today - bday
        relational_arr = relational.to_s.split('/')
        #difference = relational.to_s.split('/').chomp
        difference = relational_arr[0]
        if !!/(-)/.match(difference)
          days_till = difference.to_i.abs
          puts "\nAwesome! Your birthday is in #{days_till} days! Happy Birthday in advance!"
        else
          bday_next_year = 365 - difference.to_i.abs
          print "\nAwesome! Your birthday is in #{bday_next_year} days! Happy birthday in advance!"
        end
      else
        print "You gave an invalid date!"
      end
    else
      print "I'd cheer for you, if only I knew who you were :("
      puts "I would wish you a Happy Birthday, if I knew when that was!"
    end
  end
end

